#
# ~/.bash_profile
#

if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]
then
	ssh-agent -s > /tmp/ssh.keys
	. /tmp/ssh.keys
	rm /tmp/ssh.keys

	startx
fi

PATH="$PATH:/home/dralagen/.scripts/"

[[ -f ~/.bashrc ]] && . ~/.bashrc

